### ISSUE TITLE
Mongodb Connect to database error

### ISSUE THREAD

**Issue by mauryaratan** [addyosmani/backbone-fundamentals#370]
Hello,
I followed every single aspect but in Chapter 2 while connecting to Mongodb database, I get the following error:

```
events.js:71
    throw arguments[1]; // Unhandled 'error' event
                   ^
Error: failed to connect to [localhost:27017]
at Server.connect.connectionPool.on.server._serverState (/Users/ramratanmaurya/Sites/lab/bb2/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:569:74)
at EventEmitter.emit (events.js:126:20)
at connection.on._self._poolState (/Users/ramratanmaurya/Sites/lab/bb2/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:139:15)
at EventEmitter.emit (events.js:99:17)
at Socket.errorHandler (/Users/ramratanmaurya/Sites/lab/bb2/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:475:10)
at Socket.EventEmitter.emit (events.js:96:17)
at Socket._destroy.self.errorEmitted (net.js:329:14)
at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

Wondering if you can help me sort this out?

Thanks in advance.

**Comment by mauryaratan** [comment]
Never mind. I figured it out.

There was a problem with the .lock file, removing and repairing the monod did the job.

Thanks.

**Comment by metalaureate** [comment]
I have the exact some problem, only I have no idea what "monod" is. Could you elaborate?

My error is

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: failed to connect to [localhost:27017]
    at Server.connect.connectionPool.on.server._serverState (/Users/shill/Projects/Bookstore/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:569:74)
    at EventEmitter.emit (events.js:126:20)
    at connection.on._self._poolState (/Users/shill/Projects/Bookstore/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:139:15)
    at EventEmitter.emit (events.js:99:17)
    at Socket.errorHandler (/Users/shill/Projects/Bookstore/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:475:10)
    at Socket.EventEmitter.emit (events.js:96:17)
    at Socket._destroy.self.errorEmitted (net.js:329:14)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by metalaureate** [comment]
How about I start MongoDB? Apologies.
